export const CREATE_USER = 'app/CREATE_USER';
export const CREATE_USER_SUCCESS = 'app/CREATE_USER_SUCCESS';
export const UPDATE_USER = 'app/UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'app/UPDATE_USER_SUCCESS';